### ISSUE TITLE
Beleaguered Solitaire - selectable area of a card is abnormal at times

### ISSUE THREAD

**Issue by ChrisJenn** [SaitoTech/saito-lite-rust#1405]
This is a fairly rare occurrence. Normally, when the cursor crosses over the edge of the div for a selectable slot will result in the border of that card changing colour. In problem state, only the far right hand side of the card (when on left pile) or far left hand side of the card (when on right pile) will trigger the action. 

The cause appears to be that there is another slot div  in front which does not have the 'invisible' class applied to it

Here's an example from a pile on the left side:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/39251321/200765432-e3092cbb-21d2-49ea-a3b3-320d3444d058.png">

It can be reproduced manually by removing the invisible class from the slot above the selectable one.

example, normal state from a pile on the right side:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/39251321/200769144-37bd0f21-cb46-4399-9760-227972f0ecc9.png">

problem state after manually removing the invisible class:

<img width="384" alt="image" src="https://user-images.githubusercontent.com/39251321/200769011-5ab0eaec-74d1-4cea-9c93-c4d43c36467f.png">

**Comment by pawelpaszki** [comment]
hi. thanks for flagging this! I have noticed it as well. the code for enabling available moves is a bit overcomplicated. I will try to tackle it next week

**Comment by ChrisJenn** [comment]
A small thing, not worthy of a bug report. Can you update <html><head><title> to "Saito Beleaguered Solitaire" not "Saito Solitrio" ? Thanks

**Comment by trevelyan** [comment]
fixed.

**Comment by ChrisJenn** [comment]
Hi David, I'm still seeing the reported problem - perhaps this was closed in error?
