### ISSUE TITLE
Crypto: reference to old API in wallet

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#2329]
Game transfer (recipient) has this silent error which makes it look like they never receive the transfer

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/95d25611-cc26-4866-83f6-0cbd1ea7e878)

**Comment by umairkhannn** [comment]
Fixed in branch:  mixin/node-sdk

**Comment by f8daniel** [comment]
still seeing the error



![Image](https://github.com/SaitoTech/saito-lite-rust/assets/70703104/48cf3c75-3eb8-48ac-9826-61c763f64062)

**Comment by umairkhannn** [comment]
@f8daniel can you please list down steps on how to reproduce this.

I started 2 player chess game, initiatated crypto offer. Player 1 resigns, but couldnt see this specific error "this.mixin.fetchDeposits" in console.

**Comment by umairkhannn** [comment]
@f8daniel is this still valid? not able to reproduce this.

**Comment by f8daniel** [comment]
That should be marked done
