### ISSUE TITLE
Registered name in red square is not reflecting on the tweets name, only the public address is showing

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#908]
Test Step
1. Go to red square
2. Register your saito account
3. Tweet something
4. Post appears upon reload

Actual:
Public address appears instead of name
<img width="523" alt="image" src="https://user-images.githubusercontent.com/96273856/184585236-8dc288c3-f00f-4991-a1ea-c1dfafbfa844.png">

Expected:
Name should appear on the tweet instead of public key

<img width="530" alt="image" src="https://user-images.githubusercontent.com/96273856/184585413-0e3db26b-432c-4908-8338-57a117b9e104.png">

Impact:
It will be hard to tag users/friends to create engagement and conversation since you would always need to get their public address or know them by hard -- which is impossible, and it's hard to identify users who you interact with

**Comment by davikstone2** [comment]
Fixed with this commit:  https://github.com/SaitoTech/saito-lite-rust/commit/2c8d70db19d65f79c25b207b24f48a161e23aac7

**Comment by karlsaito** [comment]
@estapeluo  please retest

**Comment by davikstone2** [comment]
Staging updated with fix. Please test

**Comment by karlsaito** [comment]
Tested. It's now working. Please create a PR and update production @davikstone2

**Comment by davikstone2** [comment]
pull request for fix here https://github.com/SaitoTech/saito-lite-rust/pull/917

**Comment by karlsaito** [comment]
reopening since the PR has not been merged. @davikstone2 could you check the comment of @trevelyan  on the PR

**Comment by davikstone2** [comment]
Fixed with this pull request https://github.com/SaitoTech/saito-lite-rust/pull/948

**Comment by karlsaito** [comment]
@arpee , @davikstone2 , issue still persist in staging and prod environment. 

Test Step:
1. Nuke wallet
2. Register username at red square
3. Wait for more than a minute
4. Page continue to refresh, and logs error:
<img width="439" alt="image" src="https://user-images.githubusercontent.com/96273856/185540180-35ae6698-e8a4-4646-ac0d-aaed5dd69f05.png">
5. Prompt for registration appears "registering XXX@saito"
6.  NEW ISSUE FROM THIS: click create new tweet and it 's not working anymore (**workaround** - go back to arcade after registration, and back to red square)
7. If you're able to create a new tweet -- registered identifier still don't appear on the new tweets created HOWEVER the username identifier appears in the arcade

https://user-images.githubusercontent.com/96273856/185540047-c5778a32-26d7-4cba-970e-ac3711fd3428.mp4

**Comment by karlsaito** [comment]
Issue is **working on tweets found at the homepage** however, it's not working on tweet-specific posts:

**Test steps**:
1. Register a username
2.  Go to red square and create a tweet. This shows:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/96273856/185829066-80ed7c8d-89b0-4b6e-b158-7399c684b6ea.png">
3. Click a tweet
<img width="424" alt="image" src="https://user-images.githubusercontent.com/96273856/185829124-f139157c-75ad-413e-bda7-c971fbaa59cc.png">

at 3rd step, what should appear is the registered username, not the public key. 

For extra test steps when you validate your fix locally:
1. retweet a post thrice
2. click the child post on the retweet until you get to the original thread. registered username should appear not the public key

**Comment by karlsaito** [comment]
already working in prod, closing now
